accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path("delete/", views.delete, name="delete"),
    path("change_password", views.change_password, name="change_password"),
]

my_first_pjt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name="index"),
    path('articles/', include("articles.urls")),
    path('accounts/', include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

products/urls.py
from django.urls import path, include
from . import views
from django.urls import path

app_name="products"
urlpatterns = [
    path('', views.products, name="products"),
    path('<int:pk>/', views.detail, name="detail"),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/like/', views.like, name='like'),
    path('<int:hashtag_pk>/hashtag/', views.hashtag, name='hashtag'), # hashtag detail page
    path('search/', views.search, name='search'),
    ]

spartamarket/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from products import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name="index"),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('users/', include("users.urls")),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.users, name='users'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

users/models.py
from django.db import models

# Create your models here.

users/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from django.shortcuts import get_object_or_404
from django.contrib.auth import get_user_model


def users(request):
    return render(request, "users/users.html")


def profile(request, username):
    member = get_object_or_404(get_user_model(), username=username)
    context = {
        "member": member,
    }
    return render(request, "users/profile.html", context)


@require_POST
def follow(request, user_pk):
    if request.user.is_authenticated:
        member = get_object_or_404(get_user_model(), pk=user_pk)
        if request.user != member:
            if request.user in member.followers.all():
                member.followers.remove(request.user)
            else:
                member.followers.add(request.user)
        return redirect('users:profile', member.username)
    else:
        return redirect('accounts:login')

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1 class="fw-bold">{{ member.username }}님의 프로필 페이지</h1>
<div>
    <h3>회원 ID : {{ member.username }}</h3>
    <p> 이름: {{ member.first_name }} {{ member.last_name }} <br>
        가입일 : {{ member.date_joined }}</p>
    {% if member.image %}
    <img src="{{ member.image.url }}" alt="{{ member.image }}" style="width: 200px;">
    {% else %}
    <img src="{% static 'accounts/user.png' %}" style="width: 200px;">
    {% endif %}
    {% if request.user != member %}
        <form action="{% url 'users:follow' member.pk %}" method="POST">
            {% csrf_token %}
            {% if request.user in member.followers.all %}
                <input type="submit" value="언팔로우">
            {% else %}
                <input type="submit" value="팔로우">
            {% endif %}
        </form>
    {% endif %}
    <p>
        팔로워 : {{ member.followers.count }}명
        팔로잉 : {{ member.following.count }}명
    </p>


    <p> 등록한 물건 <p>
        <ul>
            {% for product in member.products.all  %}
            <a href="{% url 'products:detail' product.pk %}">
            <li> 제목: {{ product.title }} </li>
            </a>
            {% endfor %}
        </ul>
    <p> 찜한 물건 <P>
        <ul>
            {% for like_product in member.like_products.all  %}
            <a href="{% url 'products:detail' like_product.pk %}">
            <li> 제목: {{ like_product }} </li>
            </a>
            {% endfor %}
        </ul>


</div>
<p>
{% if member == request.user %}
<a href="{% url "accounts:update" %}">프로필 수정</a> <br>
{% endif %}
<a href="{% url "products:products" %}">상품리스트 보기</a>
</p>
{% endblock content %}

users/templates/users/users.html
{% extends 'base.html' %}
{% block content %}
<h1 class="fw-bold">User Page</h1>
{% endblock content %}