accounts/urls.py
from django.urls import path, include
from . import views

app_name = "accounts"
urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
    path('update/', views.update, name="update"),
    path("delete/", views.delete, name="delete"),
    path("change_password", views.change_password, name="change_password"),
]

my_first_pjt/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name="index"),
    path('articles/', include("articles.urls")),
    path('accounts/', include("accounts.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

products/urls.py
from django.urls import path, include
from . import views
from django.urls import path

app_name="products"
urlpatterns = [
    path('', views.products, name="products"),
    path('<int:pk>/', views.detail, name="detail"),
    path('create/', views.create, name='create'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/like/', views.like, name='like'),
    path('<int:hashtag_pk>/hashtag/', views.hashtag, name='hashtag'), # hashtag detail page
    path('search/', views.search, name='search'),
    ]

spartamarket/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from products import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', views.index, name="index"),
    path('accounts/', include('accounts.urls')),
    path('products/', include('products.urls')),
    path('users/', include("users.urls")),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('', views.users, name='users'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
]

templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/35050ac00b.js" crossorigin="anonymous"></script>
    <title>spartamarket</title>


    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block head %}{% endblock head %}
   
</head>


<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <a class="navbar-brand ms-5" href="{% url 'index' %}">SpartaMarket</a>
        <div class="container-fluid">
            {% if request.user.is_authenticated %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-disabled="true">안녕하세요, {{ request.user.username }}님</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'users:profile' request.user.username%}">프로필</a>
                </li>
                <li class="nav-item">
                    <form action="{% url 'accounts:logout' %}" method="POST">
                        {% csrf_token %}
                        <input class="nav-link" aria-current="page" type="submit" value="로그아웃"></input>
                    </form>
                </li>
            </ul>
            <form action="{% url 'products:search' %}" method="POST" class="d-flex" role="search">
                {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="검색어를 입력하세요" name="searched" aria-label="Search">
                <button class="btn btn-danger" type="submit">Search</button>
            </form>
            {% else %}
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'accounts:login'%}">로그인</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'accounts:signup' %}">회원가입</a>
                </li>
            </ul>
            <form action="{% url 'products:search' %}" method="POST" class="d-flex" role="search">
                {% csrf_token %}
                <input class="form-control me-2" type="search" placeholder="검색어를 입력하세요" name="searched" aria-label="Search">
                <button class="btn btn-danger" type="submit">Search</button>
            </form>
        </div>
        {% endif %}
    </nav>


    <div class="container  mt-4">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
    crossorigin="anonymous"></script>
</body>
</html>